{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.pvc.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    {{- toYaml .Values.mysql.pvc.accessModes | nindent 4 }}
  storageClassName: {{ .Values.mysql.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mysql.pvc.size }}
{{- end }}

