{{- if .Values.createRdsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  username: {{ .Values.dbUsername | b64enc }}
  password: {{ .Values.dbPassword | b64enc }}
{{- end }}

